### ISSUE TITLE
Can't run with this gem installed

### ISSUE THREAD

**Issue by ariffinsetya** [airhorns/trestle-omniauth#65]
Hi I tried to install this gem and it seems, I can't make it work
```
vidioams-web-1  | => Booting Puma
vidioams-web-1  | => Rails 7.0.1 application starting in development
vidioams-web-1  | => Run `bin/rails server --help` for more startup options
vidioams-web-1  | Exiting
vidioams-web-1  | /usr/local/bundle/gems/trestle-omniauth-0.3.0/lib/trestle/omniauth/engine.rb:15:in `block in <class:Engine>': uninitialized constant Trestle::ApplicationController (NameError)
vidioams-web-1  |
vidioams-web-1  |         Trestle::ApplicationController.send(:include, Trestle::Omniauth::ControllerMethods)
vidioams-web-1  |                ^^^^^^^^^^^^^^^^^^^^^^^
vidioams-web-1  |       from /usr/local/bundle/gems/railties-7.0.1/lib/rails/initializable.rb:32:in `instance_exec'
vidioams-web-1  |       from /usr/local/bundle/gems/railties-7.0.1/lib/rails/initializable.rb:32:in `run'
vidioams-web-1  |       from /usr/local/bundle/gems/railties-7.0.1/lib/rails/initializable.rb:61:in `block in run_initializers'
vidioams-web-1  |       from /usr/local/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'
vidioams-web-1  |       from /usr/local/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
vidioams-web-1  |       from /usr/local/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from'
vidioams-web-1  |       from /usr/local/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'
vidioams-web-1  |       from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `each'
vidioams-web-1  |       from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `call'
vidioams-web-1  |       from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'
vidioams-web-1  |       from /usr/local/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each'
vidioams-web-1  |       from /usr/local/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each'
vidioams-web-1  |       from /usr/local/bundle/gems/railties-7.0.1/lib/rails/initializable.rb:60:in `run_initializers'
vidioams-web-1  |       from /usr/local/bundle/gems/railties-7.0.1/lib/rails/application.rb:372:in `initialize!'
vidioams-web-1  |       from /vidio-ams/config/environment.rb:5:in `<main>'
vidioams-web-1  |       from /usr/local/bundle/gems/bootsnap-1.10.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
vidioams-web-1  |       from /usr/local/bundle/gems/bootsnap-1.10.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
vidioams-web-1  |       from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
vidioams-web-1  |       from /usr/local/bundle/gems/bootsnap-1.10.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:42:in `require_relative'
vidioams-web-1  |       from config.ru:3:in `block in <main>'
vidioams-web-1  |       from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
vidioams-web-1  |       from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
vidioams-web-1  |       from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
vidioams-web-1  |       from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
vidioams-web-1  |       from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
vidioams-web-1  |       from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
vidioams-web-1  |       from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
vidioams-web-1  |       from /usr/local/bundle/gems/railties-7.0.1/lib/rails/commands/server/server_command.rb:76:in `log_to_stdout'
vidioams-web-1  |       from /usr/local/bundle/gems/railties-7.0.1/lib/rails/commands/server/server_command.rb:36:in `start'
vidioams-web-1  |       from /usr/local/bundle/gems/railties-7.0.1/lib/rails/commands/server/server_command.rb:143:in `block in perform'
vidioams-web-1  |       from <internal:kernel>:90:in `tap'
vidioams-web-1  |       from /usr/local/bundle/gems/railties-7.0.1/lib/rails/commands/server/server_command.rb:134:in `perform'
vidioams-web-1  |       from /usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
vidioams-web-1  |       from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
vidioams-web-1  |       from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
vidioams-web-1  |       from /usr/local/bundle/gems/railties-7.0.1/lib/rails/command/base.rb:87:in `perform'
vidioams-web-1  |       from /usr/local/bundle/gems/railties-7.0.1/lib/rails/command.rb:48:in `invoke'
vidioams-web-1  |       from /usr/local/bundle/gems/railties-7.0.1/lib/rails/commands.rb:18:in `<main>'
vidioams-web-1  |       from /usr/local/bundle/gems/bootsnap-1.10.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
vidioams-web-1  |       from /usr/local/bundle/gems/bootsnap-1.10.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
vidioams-web-1  |       from bin/rails:4:in `<main>'
```
the engine.rb can't seem to find Trestle::ApplicationController

**Comment by Awatatah** [comment]
This is still an issue as of 3/1/2023 - Any solution?

**Comment by balbesina** [comment]
solution: use github source, instead of a gem.

resolves to `0.3.0` and raises
```
gem 'trestle-omniauth'
```

resolves to `0.4.0` and works
```
gem 'trestle-omniauth', github: 'airhorns/trestle-omniauth'
```
